#release configuration
#Fri Feb 10 17:58:49 CET 2023
project.rel.guru.springframework\:sfg-pet-clinic=1
scm.commentPrefix=[maven-release-plugin] 
project.rel.org.example\:pet-clinic-web=1.0
pushChanges=true
project.scm.guru.springframework\:sfg-pet-clinic.connection=scm\:git\:git\://github.com\:EsterDaci/sfg-pet-clinic.git
project.scm.guru.springframework\:sfg-pet-clinic.url=https\://github.com/EsterDaci/sfg-pet-clinic
project.dev.org.example\:new-sfg-pet-clinic=1.1-SNAPSHOT
project.scm.org.example\:pet-clinic-web.empty=true
scm.tag=sfg-pet-clinic-1
remoteTagging=true
projectVersionPolicyId=default
project.scm.guru.springframework\:sfg-pet-clinic.developerConnection=scm\:git\:git\://github.com\:EsterDaci/sfg-pet-clinic.git
scm.url=scm\:git\:git\://github.com\:EsterDaci/sfg-pet-clinic.git
scm.tagNameFormat=@{project.artifactId}-@{project.version}
preparationGoals=clean verify
project.rel.org.example\:new-sfg-pet-clinic=1.0
project.scm.org.example\:new-sfg-pet-clinic.empty=true
project.dev.org.example\:pet-clinic-web=1.1-SNAPSHOT
exec.snapshotReleasePluginAllowed=false
project.dev.guru.springframework\:sfg-pet-clinic=2-SNAPSHOT
project.scm.guru.springframework\:sfg-pet-clinic.tag=HEAD
completedPhase=generate-release-poms
